// Generated by Wrangler on Thu Jan 02 2025 17:23:51 GMT-0700 (Mountain Standard Time)
// by running `wrangler types`

interface Env {
	MAPS_API_KEY: string;
	UPSTASH_REDIS_REST_URL: string;
	UPSTASH_REDIS_REST_TOKEN: string;
	AZ511_API_KEY: string;
	CF_PAGES: string;
}
