// Generated by Wrangler on Fri Apr 11 2025 22:05:25 GMT-0700 (Mountain Standard Time)
// by running `wrangler types`

interface Env {
	TZ: "America/Phoenix";
	UPSTASH_REDIS_REST_URL: string;
	UPSTASH_REDIS_REST_TOKEN: string;
	AZ511_API_KEY: string;
	CF_PAGES: string;
	CF_PAGES_COMMIT_SHA: string;
	TOMTOM_API_KEY: string;
}
