/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UDotjsRouteImport } from './routes/u[.js]'
import { Route as URouteImport } from './routes/u'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiRealtimeRouteImport } from './routes/api/realtime'
import { Route as ApiAlertsRouteImport } from './routes/api/alerts'
import { Route as ApiTrafficRouteRouteImport } from './routes/api/traffic/$route'
import { Route as ApiCameraIdRouteImport } from './routes/api/camera/$id'

const UDotjsRoute = UDotjsRouteImport.update({
  id: '/u.js',
  path: '/u.js',
  getParentRoute: () => rootRouteImport,
} as any)
const URoute = URouteImport.update({
  id: '/u',
  path: '/u',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRealtimeRoute = ApiRealtimeRouteImport.update({
  id: '/api/realtime',
  path: '/api/realtime',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAlertsRoute = ApiAlertsRouteImport.update({
  id: '/api/alerts',
  path: '/api/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTrafficRouteRoute = ApiTrafficRouteRouteImport.update({
  id: '/api/traffic/$route',
  path: '/api/traffic/$route',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCameraIdRoute = ApiCameraIdRouteImport.update({
  id: '/api/camera/$id',
  path: '/api/camera/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/u': typeof URoute
  '/u.js': typeof UDotjsRoute
  '/api/alerts': typeof ApiAlertsRoute
  '/api/realtime': typeof ApiRealtimeRoute
  '/api/camera/$id': typeof ApiCameraIdRoute
  '/api/traffic/$route': typeof ApiTrafficRouteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/u': typeof URoute
  '/u.js': typeof UDotjsRoute
  '/api/alerts': typeof ApiAlertsRoute
  '/api/realtime': typeof ApiRealtimeRoute
  '/api/camera/$id': typeof ApiCameraIdRoute
  '/api/traffic/$route': typeof ApiTrafficRouteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/u': typeof URoute
  '/u.js': typeof UDotjsRoute
  '/api/alerts': typeof ApiAlertsRoute
  '/api/realtime': typeof ApiRealtimeRoute
  '/api/camera/$id': typeof ApiCameraIdRoute
  '/api/traffic/$route': typeof ApiTrafficRouteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/u'
    | '/u.js'
    | '/api/alerts'
    | '/api/realtime'
    | '/api/camera/$id'
    | '/api/traffic/$route'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/u'
    | '/u.js'
    | '/api/alerts'
    | '/api/realtime'
    | '/api/camera/$id'
    | '/api/traffic/$route'
  id:
    | '__root__'
    | '/'
    | '/u'
    | '/u.js'
    | '/api/alerts'
    | '/api/realtime'
    | '/api/camera/$id'
    | '/api/traffic/$route'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  URoute: typeof URoute
  UDotjsRoute: typeof UDotjsRoute
  ApiAlertsRoute: typeof ApiAlertsRoute
  ApiRealtimeRoute: typeof ApiRealtimeRoute
  ApiCameraIdRoute: typeof ApiCameraIdRoute
  ApiTrafficRouteRoute: typeof ApiTrafficRouteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/u.js': {
      id: '/u.js'
      path: '/u.js'
      fullPath: '/u.js'
      preLoaderRoute: typeof UDotjsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u': {
      id: '/u'
      path: '/u'
      fullPath: '/u'
      preLoaderRoute: typeof URouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/realtime': {
      id: '/api/realtime'
      path: '/api/realtime'
      fullPath: '/api/realtime'
      preLoaderRoute: typeof ApiRealtimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/alerts': {
      id: '/api/alerts'
      path: '/api/alerts'
      fullPath: '/api/alerts'
      preLoaderRoute: typeof ApiAlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/traffic/$route': {
      id: '/api/traffic/$route'
      path: '/api/traffic/$route'
      fullPath: '/api/traffic/$route'
      preLoaderRoute: typeof ApiTrafficRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/camera/$id': {
      id: '/api/camera/$id'
      path: '/api/camera/$id'
      fullPath: '/api/camera/$id'
      preLoaderRoute: typeof ApiCameraIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  URoute: URoute,
  UDotjsRoute: UDotjsRoute,
  ApiAlertsRoute: ApiAlertsRoute,
  ApiRealtimeRoute: ApiRealtimeRoute,
  ApiCameraIdRoute: ApiCameraIdRoute,
  ApiTrafficRouteRoute: ApiTrafficRouteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
